# Generated by Django 2.2.5 on 2019-11-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20191128_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='is_mobile',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
